version: '3.1'

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: application-api
    networks:
      api-network:
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: application-nginx
    ports:
      - "80:80"
    networks:
      api-network:
    depends_on:
      - api

  db:
    image: mysql:5.7
    container_name: application-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=application-db
    restart: always
    volumes:
      - ./db/:/var/lib/mysql
      - ./db/initial-scripts/:/docker-entrypoint-initdb.d/
    networks:
      api-network:
    expose:
      - 3306

networks:
  api-network: